### ISSUE TITLE
Errors with OpenSea call 

### ISSUE THREAD

**Issue by ricoxor** [cawfree/sameorigin#3]
Hello, 
Trying to use this for OpenSea Open Graph but I have errors.

```
const [axios, { close }] = await sameorigin({
  squatURL: 'https://opensea.io/fr/collection/mutant-ape-yacht-club/activity',
});

const { data } = await axios({
  baseURL: 'https://opensea.io/__api',
  url: '/graphql',
  method: 'post',
  headers: {
    'Content-Type': 'application/json'
  },
  data: '{"id":"CollectionInfoPollingQuery","query":"query CollectionInfoPollingQuery(\n  $collection: CollectionSlug!\n) {\n  collection(collection: $collection) {\n    ...CollectionInfoInnerPoll_data\n    id\n  }\n}\n\nfragment CollectionInfoInnerPoll_data on CollectionType {\n  ...collection_poll_stats\n}\n\nfragment collection_poll_stats on CollectionType {\n  statsV2 {\n    totalListed\n  }\n  collectionOffers(first: 1) {\n    edges {\n      node {\n        perUnitPriceType {\n          unit\n          symbol\n        }\n        id\n      }\n    }\n  }\n}\n","variables":{"collection":"mutant-ape-yacht-club"}}'
});
```

The request return an error :

```
data: '<!DOCTYPE html>\n' +
      '<html lang="en">\n' +
      '<head>\n' +
      '<meta charset="utf-8">\n' +
      '<title>Error</title>\n' +
      '</head>\n' +
      '<body>\n' +
      '<pre>SyntaxError: Unexpected token &quot; in JSON at position 0<br> &nbsp; &nbsp;at JSON.parse (&lt;anonymous&gt;)<br> &nbsp; &nbsp;at createStrictSyntaxError (C:\\Users\\Romain\\Sites\\test\\node_modules\\body-parser\\lib\\types\\json.js:169:10)<br> &nbsp; &nbsp;at parse (C:\\Users\\Romain\\Sites\\test\\node_modules\\body-parser\\lib\\types\\json.js:86:15)<br> &nbsp; &nbsp;at C:\\Users\\Romain\\Sites\\test\\node_modules\\body-parser\\lib\\read.js:128:18<br> &nbsp; &nbsp;at AsyncResource.runInAsyncScope (node:async_hooks:203:9)<br> &nbsp; &nbsp;at invokeCallback (C:\\Users\\Romain\\Sites\\test\\node_modules\\raw-body\\index.js:238:16)<br> &nbsp; &nbsp;at done (C:\\Users\\Romain\\Sites\\test\\node_modules\\raw-body\\index.js:227:7)<br> &nbsp; &nbsp;at IncomingMessage.onEnd (C:\\Users\\Romain\\Sites\\test\\node_modules\\raw-body\\index.js:287:7)<br> &nbsp; &nbsp;at IncomingMessage.emit (node:events:513:28)<br> &nbsp; &nbsp;at endReadableNT (node:internal/streams/readable:1359:12)</pre>\n' +
      '</body>\n' +
      '</html>\n'
  }
```

Do you have any ideas to fix thix ?

**Comment by cawfree** [comment]
I think the issue here is that you were passing `data` as a `string` instead of a JSON object.

This should work:

```typescript
const [axios] = await sameorigin({
  squatURL: 'https://opensea.io',
  port: 3006,
});

const {data} = await axios({
  baseURL: 'https://opensea.io/__api/graphql/',
  method: 'post',
  headers: {
    'x-app-id': 'opensea-web',
    'x-build-id': 'ca843d0cef60c1a3a54dde5c9b8d150c19fecd20',
    'x-signed-query': '811271738cb69acac9374881b66dbfb7743b667aeb4fdd8c24f148c75a11423b',
  },
  data: {"id":"CollectionInfoPollingQuery","query":"query CollectionInfoPollingQuery(\n  $collection: CollectionSlug!\n) {\n  collection(collection: $collection) {\n    ...CollectionInfoInnerPoll_data\n    id\n  }\n}\n\nfragment CollectionInfoInnerPoll_data on CollectionType {\n  ...collection_poll_stats\n}\n\nfragment collection_poll_stats on CollectionType {\n  statsV2 {\n    totalListed\n  }\n  collectionOffers(first: 1) {\n    edges {\n      node {\n        perUnitPriceType {\n          unit\n          symbol\n        }\n        id\n      }\n    }\n  }\n}\n","variables":{"collection":"mutant-ape-yacht-club"}},
});

console.log(JSON.stringify(data));
```
